version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20

  pre_build:
    commands:
      - echo "=== directory check ==="
      - ls -al
      - ls -al frontend
      - ls -al backend

      - cd frontend
      - npm install
      - cd ../backend
      - chmod +x gradlew

  build:
    commands:
      - echo "=== frontend build ==="
      - cd $CODEBUILD_SRC_DIR/frontend
      - npm run build

      - echo "=== backend build ==="
      - cd $CODEBUILD_SRC_DIR/backend
      - ./gradlew clean build -x test

artifacts:
  base-directory: frontend/dist
  files:
    - '**/*'
    - ../../backend/build/libs/*.jar
  discard-paths: no