version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
    commands:
      - echo "Install phase"

  pre_build:
    commands:
      - echo "Installing frontend dependencies"
      - cd frontend
      - npm ci
      - cd ../backend
      - chmod +x gradlew

  build:
    commands:
      - echo "Building frontend"
      - cd ../frontend
      - npm run build
      - echo "Building backend"
      - cd ../backend
      - ./gradlew clean build -x test

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - backend/build/libs/*.jar
    - frontend/dist/**/*
    - 'dist/test-angular-project/**/*'
    - appspec.yml
    - 'deploy-scripts/**/*'
  discard-paths: no