version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - cd frontend
      - npm install

  build:
    commands:
      - cd frontend
      - npx ng test --no-watch --no-progress